# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jieba_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jieba_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13jieba_service.proto\"P\n\nCutRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x0f\n\x07\x63ut_all\x18\x02 \x01(\x08\x12\x0b\n\x03HMM\x18\x03 \x01(\x08\x12\x12\n\nuse_paddle\x18\x04 \x01(\x08\"\x1c\n\x08\x43utReply\x12\x10\n\x08seg_list\x18\x01 \x01(\t2/\n\x0cJiebaService\x12\x1f\n\x03\x63ut\x12\x0b.CutRequest\x1a\t.CutReply\"\x00\x62\x06proto3')
)




_CUTREQUEST = _descriptor.Descriptor(
  name='CutRequest',
  full_name='CutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='CutRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cut_all', full_name='CutRequest.cut_all', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HMM', full_name='CutRequest.HMM', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_paddle', full_name='CutRequest.use_paddle', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=103,
)


_CUTREPLY = _descriptor.Descriptor(
  name='CutReply',
  full_name='CutReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seg_list', full_name='CutReply.seg_list', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['CutRequest'] = _CUTREQUEST
DESCRIPTOR.message_types_by_name['CutReply'] = _CUTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CutRequest = _reflection.GeneratedProtocolMessageType('CutRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUTREQUEST,
  '__module__' : 'jieba_service_pb2'
  # @@protoc_insertion_point(class_scope:CutRequest)
  })
_sym_db.RegisterMessage(CutRequest)

CutReply = _reflection.GeneratedProtocolMessageType('CutReply', (_message.Message,), {
  'DESCRIPTOR' : _CUTREPLY,
  '__module__' : 'jieba_service_pb2'
  # @@protoc_insertion_point(class_scope:CutReply)
  })
_sym_db.RegisterMessage(CutReply)



_JIEBASERVICE = _descriptor.ServiceDescriptor(
  name='JiebaService',
  full_name='JiebaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=182,
  methods=[
  _descriptor.MethodDescriptor(
    name='cut',
    full_name='JiebaService.cut',
    index=0,
    containing_service=None,
    input_type=_CUTREQUEST,
    output_type=_CUTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JIEBASERVICE)

DESCRIPTOR.services_by_name['JiebaService'] = _JIEBASERVICE

# @@protoc_insertion_point(module_scope)
