# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import jieba_service_pb2 as jieba__service__pb2


class JiebaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.cut = channel.unary_unary(
        '/JiebaService/cut',
        request_serializer=jieba__service__pb2.CutRequest.SerializeToString,
        response_deserializer=jieba__service__pb2.CutReply.FromString,
        )


class JiebaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def cut(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JiebaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'cut': grpc.unary_unary_rpc_method_handler(
          servicer.cut,
          request_deserializer=jieba__service__pb2.CutRequest.FromString,
          response_serializer=jieba__service__pb2.CutReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'JiebaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
