from ubuntu:18.04

RUN apt update && apt install -y curl && \
    curl -o k3s -sfL https://github.com/rancher/k3s/releases/download/v1.0.1/k3s && \
    curl -o k3s-airgap-images-amd64.tar -sfL https://github.com/rancher/k3s/releases/download/v1.0.1/k3s-airgap-images-amd64.tar


