from tensorflow/tensorflow:1.4.0-py3

RUN echo "/root/models/research/" | tee /usr/local/lib/python3.5/dist-packages/research.pth \
   && echo "/root/models/research/slim" | tee /usr/local/lib/python3.5/dist-packages/slim.pth \

