FROM python:3.7.6-alpine

RUN wget https://dl.fbaipublicfiles.com/m2m_100/model_dict.128k.txt && \
    wget https://dl.fbaipublicfiles.com/m2m_100/language_pairs_small_models.txt && \
    wget https://dl.fbaipublicfiles.com/m2m_100/418M_last_checkpoint.pt && \
    wget https://dl.fbaipublicfiles.com/m2m_100/1.2B_last_checkpoint.pt
