version: '3'
services:
    py-demo:
        image: python:3.7.6-alpine
        command: ["python", "-u", "demo_server.py"]
        restart: always
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            TZ: Asia/Shanghai
        
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 100M
                reservations:
                    cpus: '0.5'
                    memory: 10M